### ISSUE TITLE
Blank preview - Not working on OSX?

### ISSUE THREAD

**Issue by tauren** [AleksandarDev/vscode-sequence-diagrams#2] opened 2017-09-12 23:02 UTC
I've installed this plugin, created a `sample.seqdiag` file, and added a simple sequence from the project samples to it:

```
Andrew->China: Says Hello
```

When I preview it (Command+Shift+P -> Show Sequence Diagram Preview), the preview panel opens with a message something like "Not a sequence diagram", but the message immediately goes away and leaves a blank preview panel. 

I'm using vscode 1.16.0 on OSX, with version 0.2.0 of the plugin. No matter what I try, the preview panel is always blank. Has it been tested on OSX?

**Comment by AleksandarDev** [comment] 2017-09-13 07:22
@tauren The extension was only tested on Windows 10 machines. I will try to reproduce this issue today on Mac. Thanks for reporting.

**Comment by AleksandarDev** [comment] 2017-09-13 11:59
@tauren This should be fixed with new version `0.2.1`. Can you please confirm the issue is resolved?

**Comment by tauren** [comment] 2017-09-20 06:59
Works on OSX now, thanks!

**Comment by merikan** [comment] 2017-11-30 07:55
Is this really working on MacOS? My preview is blank (empty).
Installed version 0.2.1 on MacOS 10.12.6

**Comment by AleksandarDev** [comment] 2017-11-30 10:45
Hi @merikan,

If you are presented with blank preview somehing is wrong indeed. You should atleast have
 `Not a sequence diagram document. Sequence diagram document needs to have .seqdiag extension.` message in preview window.

I don't have Mac to test the extension on so it would be great if you could provide me with more details about the problem.

Can you:

- [ ] open the developer tools in VSCode (under Help > Toggle Developer Tools)
- [ ] switch to Console in the developer tools
- [ ] load the file you are having trouble with 
- [ ] grab a screenshot of the errors

And report back with the data.

**Comment by merikan** [comment] 2017-11-30 20:31
@AleksandarDev I'm sorry but I used the wrong syntax. I usually use https://www.websequencediagrams.com/ and thought it was the same syntax. After I changed the syntax, the chart appears in preview tab. 

Awesome plugin. Thx

**Comment by AleksandarDev** [comment] 2017-11-30 22:20
I see you'we opened new issue #7 , was about to suggest you do that, great. 

Thanks for the nice words.

**Closed as completed by AleksandarDev** 2017-11-30 22:20 UTC
Labels: bug
