### ISSUE TITLE
v0.4.1 not rendering diagram

### ISSUE THREAD

**Issue by justinbowes** [AleksandarDev/vscode-sequence-diagrams#26] opened 2020-11-23 17:30 UTC
Downgrading to v0.4.0 resolves the issue.

VS Code:
--
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-54-generic snap

**Comment by AleksandarDev** [comment] 2020-12-15 12:49
Duplicate of #23 . Closing

**Closed as completed by AleksandarDev** 2020-12-15 12:49 UTC
